main/admin_ui/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', main_page, name='main_page'),
    path('admin_ui/clients/', Client_list.as_view(), name='client_list'),
    path('admin_ui/clients/create/', CreateClient.as_view(), name='client_create_admin'),
    path('admin_ui/clients/<int:pk>/update/', UpdateClient.as_view(), name='client_update_admin'),
    path('admin_ui/clients/<int:pk>/delete/', DeleteClient.as_view(), name='client_delete_admin'),
    path('admin_ui/mailings/', Mailing_list.as_view(), name='mailings_list'),
    path('admin_ui/mailings/create/', CreateMailing.as_view(), name='mailings_create_admin'),
    path('admin_ui/mailings/<int:pk>/update/', UpdateMailing.as_view(), name='mailings_update_admin'),
    path('admin_ui/mailings/<int:pk>/delete/', DeleteMailing.as_view(), name='mailings_delete_admin'),
    path('admin_ui/mailings/settings_email/', SettingsEmailingStat.as_view(), name='settings_email'),
    path('admin_ui/mailings/<int:pk>/statistic/', Mailing_statistic.as_view(), name='mailings_statistic'),
    path('admin_ui/logs', Logs_list.as_view(), name='logs'),
    path("", index, name="index"),
    path("login", login, name="login"),
    path("logout", logout, name="logout"),
    path("callback", callback, name="callback"),
]

main/main/urls.py
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

from django.contrib import admin
from django.urls import path, include
from rest_framework import permissions

schema_view = get_schema_view(
    openapi.Info(
        title="Snippets API",
        default_version='v1',
        description="Test description",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="contact@snippets.local"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
    path('', include('admin_ui.urls')),
    path('admin/', admin.site.urls),
    path('apiv1/', include('notification.urls')),
    path('docs/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
    path('', include('django_prometheus.urls')),
]

main/admin_ui/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.


class HistoryDataForEmailingStat(models.Model):
    email = models.CharField(max_length=255)
    date = models.DateTimeField()
    task_id = models.CharField(max_length=255)


class Logs(models.Model):
    endpoint = models.CharField(max_length=100, null=True)
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    response_code = models.PositiveSmallIntegerField()
    method = models.CharField(max_length=10, null=True)
    remote_address = models.CharField(max_length=20, null=True)
    exec_time = models.IntegerField(null=True)
    date = models.DateTimeField(auto_now=True)
    body_response = models.TextField()
    body_request = models.TextField()

main/admin_ui/forms.py
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Field
from django.forms import ModelForm, DateTimeInput, DateTimeField, forms
from tempus_dominus.widgets import DatePicker, TimePicker, DateTimePicker

from notification.models import Mailing


class MailingForm(ModelForm):
    class Meta:
        model = Mailing
        fields = ['date_dispatch', 'date_stop', 'description', 'text', 'tags', 'mobile_operator']
        widgets = {
            'date_dispatch': DateTimePicker(
                options={
                    'useCurrent': True,
                    'collapse': False,
                },
                attrs={
                    'append': 'fa fa-calendar',
                    'icon_toggle': True,
                }
            ),
            'date_stop': DateTimePicker(
                options={
                    'useCurrent': True,
                    'collapse': False,
                },
                attrs={
                    'append': 'fa fa-calendar',
                    'icon_toggle': True,
                }
            ),
        }

main/admin_ui/views.py
import datetime
import json
import time

import pytz
from authlib.integrations.django_client import OAuth
from django.conf import settings
from django.shortcuts import redirect, render, redirect
from django.urls import reverse
from urllib.parse import quote_plus, urlencode
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect

# Create your views here.
# View для главной страницы
from django.shortcuts import render
from django.urls import reverse, reverse_lazy
from django.views import View
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, DetailView

from admin_ui.forms import MailingForm
from main.celery import app
from .tasks import *
from admin_ui.models import HistoryDataForEmailingStat, Logs
from notification.models import Client, MobileOperator, Mailing
from notification.tasks import *


def main_page(request):
    mailings = Mailing.objects.filter(date_dispatch__gte=datetime.datetime.now(tz=pytz.timezone("Europe/Moscow")))[:5]
    return render(request, 'notification/main_page.html', {'mailings': mailings})


# View для редактирования ежедневной рассылки, создает новую повторяющуюся задачу celery и отменяет старую
class SettingsEmailingStat(View):
    def get(self, request):
        data = HistoryDataForEmailingStat.objects.last()
        return render(request, 'admin_ui/another/statictic_email.html', {'data': data})

    def post(self, request):
        data = HistoryDataForEmailingStat.objects.last()
        if data != None:
            app.control.revoke(data.task_id, terminate=True)
        new_task = HistoryDataForEmailingStat(email=request.POST['email'],
                                              date=request.POST['datetime'],
                                              )
        new_task.save()
        time_now = datetime.datetime.now()
        print(new_task.date)
        time_start = new_task.date
        time_start = datetime.datetime.strptime(time_start, "%Y-%m-%dT%H:%M")
        delay = (time_start - time_now).total_seconds()
        m = send_statistic.apply_async((new_task.date, new_task.email),
                                       countdown=delay)
        new_task.task_id = m.id
        new_task.save()
        data = HistoryDataForEmailingStat.objects.last()
        return render(request, 'admin_ui/another/statictic_email.html', {'data': data})


class Mailing_statistic(DetailView):
    model = Mailing
    template_name = "admin_ui/mailing/mailing_statistic.html"
    context_object_name = 'mailing'

    def get_context_data(self, **kwargs):
        context = super(Mailing_statistic,self).get_context_data(**kwargs)
        context['messages'] = Message.objects.filter(mailing_id=self.kwargs['pk']).values('status').annotate(
            count=Count('status'))
        return context

class Logs_list(ListView):
    model = Logs
    template_name = 'admin_ui/logs.html'
    context_object_name = 'logs'
    ordering = ['-date']

class Client_list(ListView):
    model = Client
    template_name = 'admin_ui/client/client_list.html'
    context_object_name = 'clients'


class CreateClient(CreateView):
    model = Client
    template_name = 'admin_ui/client/client_create.html'
    fields = ['name', 'phone_number', 'tags']
    success_url = reverse_lazy('client_list')

    def form_valid(self, form):
        self.object = form.save()
        number = self.object.phone_number
        if '+' in number:
            mobile_operator = number[1:4]
        else:
            mobile_operator = number[0:3]
        self.object.mobile_operator = MobileOperator.objects.get_or_create(code=mobile_operator)[0]
        self.object = form.save()
        return HttpResponseRedirect(self.get_success_url())


class UpdateClient(UpdateView):
    model = Client
    template_name = 'admin_ui/client/client_update.html'
    fields = ['name', 'phone_number', 'tags']
    success_url = reverse_lazy('client_list')

    def form_valid(self, form):
        self.object = form.save()
        number = self.object.phone_number
        if '+' in number:
            mobile_operator = number[1:4]
        else:
            mobile_operator = number[0:3]
        self.object.mobile_operator = MobileOperator.objects.get_or_create(code=mobile_operator)[0]
        self.object = form.save()
        return HttpResponseRedirect(self.get_success_url())


class DeleteClient(DeleteView):
    model = Client
    template_name = 'admin_ui/client/client_delete.html'
    success_url = reverse_lazy('client_list')


class Mailing_list(ListView):
    model = Mailing
    template_name = 'admin_ui/mailing/mailing_list.html'
    context_object_name = 'mailings'


class CreateMailing(CreateView):
    model = Mailing
    template_name = 'admin_ui/mailing/mailing_create.html'
    success_url = reverse_lazy('mailings_list')
    form_class = MailingForm

    def form_valid(self, form):
        self.object = form.save()
        """
        если время завершения рассылки меньше текущего, рассылка не стартует!
        если время старта в будущем , создается задача с началом на время старта!
        если время старта в прошлом или текущее, а время до завершения еще осталось,
        рассылка стартует немедленно!
        """
        now = datetime.datetime.now(tz=pytz.timezone("Europe/Moscow"))
        print(now)
        stop = self.object.date_stop
        start = self.object.date_dispatch
        if stop > now:
            m = send_create_message.apply_async((self.object.id,), countdown=(start - now).total_seconds())
            self.object.id_task = m.id
            self.object = form.save()
        return HttpResponseRedirect(self.get_success_url())



class UpdateMailing(UpdateView):
    model = Mailing
    template_name = 'admin_ui/mailing/mailing_update.html'
    success_url = reverse_lazy('mailings_list')
    form_class = MailingForm

    def form_valid(self, form):
        self.object = form.save()
        """
            При редактировании старая задача удаляется, новая создается.ю
        """
        now = datetime.datetime.now(tz=pytz.timezone("Europe/Moscow"))
        stop = self.object.date_stop
        start = self.object.date_dispatch
        if stop > now:
            app.control.revoke(self.object.id_task, terminate=True)
            m = send_create_message.apply_async((self.object.id,), countdown=(start - now).total_seconds())
            self.object.id_task = m.id
            self.object = form.save()
        return HttpResponseRedirect(self.get_success_url())


class DeleteMailing(DeleteView):
    model = Mailing
    template_name = 'admin_ui/mailing/mailing_delete.html'
    success_url = reverse_lazy('mailings_list')

    def form_valid(self, form):
        # удаляем задачу
        app.control.revoke(self.object.id_task, terminate=True)
        self.object.delete()
        return HttpResponseRedirect(self.get_success_url())


# Авторизация через OAuth
oauth = OAuth()

oauth.register(
    "auth0",
    client_id="CT7sFrzdeKbhskHyVQR4LtX1JrKiN1np",
    client_secret="aab5VbwxQFGCuwXeYmT3_VxLBosWUfp3MmBbJ8dZgPjcENcUIfyR2ajxgpJbMlMB",
    client_kwargs={
        "scope": "openid profile email",
    },
    server_metadata_url=f"https://dev-ybcgufs86ymu7uge.us.auth0.com/.well-known/openid-configuration",
)


def index(request):
    return render(
        request,
        "index.html",
        context={
            "session": request.session.get("user"),
            "pretty": json.dumps(request.session.get("user"), indent=4),
        },
    )


def callback(request):
    token = oauth.auth0.authorize_access_token(request)
    request.session["user"] = token
    return redirect(request.build_absolute_uri(reverse("index")))


def login(request):
    return oauth.auth0.authorize_redirect(
        request, request.build_absolute_uri(reverse("callback"))
    )


def logout(request):
    request.session.clear()

    return redirect(
        f"https://dev-ybcgufs86ymu7uge.us.auth0.com/v2/logout?"
        + urlencode(
            {
                "returnTo": request.build_absolute_uri(reverse("index")),
                "client_id": "CT7sFrzdeKbhskHyVQR4LtX1JrKiN1np",
            },
            quote_via=quote_plus,
        ),
    )

main/templates/admin_ui/mailing/mailing_create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<h3 class="text-center">Создание рассылки</h3>
<div class="container">
<form method="post">
    {% csrf_token %}
    {{form|crispy}}
    <br/>
    <button class="btn btn-primary" type="submit">Создать</button>
    <a href="{% url 'mailings_list' %}" class="btn btn-primary"> Отмена</a>
</form>
</div>
<script>
  $(function () {
    $("#id_date").datetimepicker({
      format: 'd/m/Y H:i',
    });
  });
</script>
{% endblock content %}

main/templates/admin_ui/mailing/mailing_delete.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<h3 class="text-center">Удаление  рассылки</h3>
<div class="container">
<form method="post">
  {% csrf_token %}
  {{form|crispy}}
  <h4>Вы действительно хотите удалить?</h4>
  <br/>
  <button class="btn btn-danger" type="submit">Удалить</button>
  <a href="{% url 'mailings_list' %}" class="btn btn-primary"> Отмена</a>
</form>
</div>
{% endblock content %}

main/templates/admin_ui/mailing/mailing_list.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <a class="btn btn-primary" href="{% url 'mailings_create_admin' %}">Добавить</a>
    <table class="table">
        <thead>
        <tr>
            <th scope="col">id</th>
            <th scope="col">Описание</th>
            <th scope="col">Дата рассылки</th>
            <th scope="col">Дата завершения рассылки</th>
            <th scope="col">Теги</th>
            <th scope="col">Операторы</th>
            <th>Редактировать</th>
        </tr>
        </thead>
        <tbody>
        {% for mailing in mailings %}
        <tr>
            <th scope="row">{{mailing.id}}</th>
            <td>{{mailing.description}}</td>
            <td>{{mailing.date_dispatch}}</td>
            <td>{{mailing.date_stop}}</td>
            <td>
                {% for tag in mailing.tags.all %}
                <p>{{tag}}</p>
                {% endfor %}
            </td>
            <td>
                {% for mobile_operator in mailing.mobile_operator.all %}
                <p>{{mobile_operator}}</p>
                {% endfor %}
            </td>

            <td>
                <a class="btn btn-warning" href="{% url 'mailings_update_admin' pk=mailing.pk %}">Редактировать</a>
                <a class="btn btn-danger" href="{% url 'mailings_delete_admin' pk=mailing.pk %}">Удалить</a>
                <a class="btn btn-primary" href="{% url 'mailings_statistic' pk=mailing.pk %}">Статистика</a>
            </td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
{% endblock content %}

main/templates/admin_ui/mailing/mailing_statistic.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<h3 class="text-center">Статистика рассылки</h3>
<div class="container">
    <p class="form-control">Наименование:{{mailing.description}}</p>
    <p class="form-control">Дата начала:{{mailing.date_dispatch}}</p>
    <p class="form-control">Дата завершения:{{mailing.date_stop}}</p>
    <p>Информация по сообщениям</p>
    {% for i in messages %}
    <p class="form-control">{{i.status}}:{{i.count}}</p>
    {% endfor %}
</div>
{% endblock content %}

main/templates/admin_ui/mailing/mailing_update.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class="container">
<h3 class="text-center">Редактирование рассылки</h3>
<form method="post">
    {% csrf_token %}
    {{form|crispy}}
    <br/>
    <button class="btn btn-primary" type="submit">Редактировать</button>
    <a href="{% url 'mailings_list' %}" class="btn btn-primary"> Отмена</a>
</form>
</div>
<script>
</script>
{% endblock content %}